<?php
// auth-generated by init
// date: 03/18/2015 19:53:29
if (!defined('ROOT_DIR')) { define('ROOT_DIR', '/home/fluxfe/examples/rehab/docroot'); }
if (!defined('DOCROOT_DIR')) { define('DOCROOT_DIR', '/home/fluxfe/examples/rehab/docroot'); }
if (!defined('FLOW_CACHE_DIR')) { define('FLOW_CACHE_DIR', '/home/fluxfe/examples/rehab/docroot/.cache/'); }
if (!defined('LIB_DIR')) { define('LIB_DIR', '/home/fluxfe/examples/rehab/lib'); }
if (!defined('FE_LIB_DIR')) { define('FE_LIB_DIR', '/home/fluxfe/frontend/webapp/lib'); }
if (!defined('MO_API_URL')) { define('MO_API_URL', 'http://api.flux.local'); }
if (!defined('OFFER_KEY')) { define('OFFER_KEY', '26'); }
if (!defined('COOKIE_NAME')) { define('COOKIE_NAME', 'flux_26'); }
if (!defined('DEFAULT_CAMPAIGN_ID')) { define('DEFAULT_CAMPAIGN_ID', '54b6e890319ac8e7643d3478'); }
?>