<center><br>TERMS OF USE<br><br></center>

<br>PLEASE READ THESE TERMS OF USE CAREFULLY. THIS IS A BINDING AGREEMENT. BY USING THE SITE, OR ANY PRODUCTS OR SERVICES PROVIDED IN CONNECTION WITH THE SITE, YOU AGREE TO ABIDE BY THESE TERMS OF USE, AS THEY MAY BE AMENDED BY Rehab-Connect FROM TIME TO TIME IN ITS SOLE DISCRETION. YOU AGREE THAT BY USING THE SITE YOU REPRESENT THAT YOU ARE AT LEAST 18 YEARS OLD AND THAT YOU ARE LEGALLY ABLE TO ENTER INTO THIS AGREEMENT.
<br><br>
These Terms of Use ("Terms") apply to your access to, and use of, any website of Rehab-Connect, including http://socal-recovery.org (the "Site"). These Terms do not alter in any way the terms or conditions of any other agreement you may have with Rehab-Connect, or its subsidiaries or affiliates, for products, services or otherwise. If you are using the Site on behalf of any entity, you represent and warrant that you are authorized to accept these Terms on such entity's behalf, and that such entity agrees to indemnify you and Rehab-Connect for violations of these Terms.
<br><br>
1. Privacy Policy
<br>
Please refer to our Privacy Policy for information about how Rehab-Connect collects, uses and discloses personal information from its users.
<br>
2. Eligibility, Registration and Account
<br>
By accessing or using the Site, you represent and warrant that you are a resident of the United States and at least 18 years old. If you are not 18 or older, you may only use the Site under the supervision of a parent or legal guardian who agrees to be bound by these Terms.
<br>
In order to access certain areas and features of our Site, you will need to register for an account. You agree to (a) provide accurate, truthful, current and complete information when creating an account; (b) maintain and promptly update your account information; (c) maintain the security of your account by not sharing your password with others and restricting access to your account and your computer; (d) promptly notify Rehab-Connect if you discover or otherwise suspect any security breaches related to the Site; and (e) take responsibility for all activities that occur under your account and accept all risks of unauthorized access.
<br>
3. Copyright and Limited License
<br>
Unless otherwise indicated, the Site and all content and other materials on the Site, including, without limitation, the Rehab-Connect logo, and all designs, text, graphics, pictures, information, data, software, sound files, other files and the selection and arrangement thereof (collectively, the "Site Materials") are the proprietary property of Rehab-Connect or its licensors or users and are protected by U.S. and international copyright laws.
<br>
All contents of the Site are: Copyright © 2014 Rehab-Connect, 24310 Moulton Pkwy O-198 Laguna Hills, CA 92637. All rights reserved.
<br>
You are granted a limited, non-transferable, non-exclusive license to access and use the Site and Site Materials; provided, however, that such license is subject to these Terms of Use and does not include: (a) any resale or commercial use of the Site or the Site Materials therein; (b) the distribution, public performance or public display of any Site Materials; (c) modifying or otherwise making any derivative uses of the Site and the Site Materials, or any portion thereof, unless modification or derivative use is specifically provided for under separate terms; (d) use of any data mining, robots or similar data gathering or extraction methods; (e) downloading (other than page caching) of any portion of the Site, the Site Materials or any information contained therein, except as expressly permitted on the Site; or (f) any use of the Site or the Site Materials other than for its intended purpose. Any use of the Site or the Site Materials other than as specifically authorized herein, without the prior written permission of Rehab-Connect, is strictly prohibited and will terminate the license granted herein. Such unauthorized use may also violate applicable laws including without limitation copyright and trademark laws and applicable communications regulations and statutes. Unless explicitly stated herein, nothing in these Terms of Use will be construed as conferring any license to intellectual property rights, whether by estoppel, implication or otherwise. This license is revocable at any time.
<br>
4. Copyright Infringement
<br>
Rehab-Connect has in place certain legally mandated procedures regarding allegations of copyright infringement occurring on the Site. Rehab-Connect has adopted a policy that provides for the immediate suspension and/or termination of any Site user who is found to have infringed on the rights of Rehab-Connect or of a third party, or otherwise violated any intellectual property laws or regulations. Rehab-Connect's policy is to investigate any allegations of copyright infringement brought to its attention. If you have evidence, know, or have a good faith belief that your rights or the rights of a third party have been violated and you want Rehab-Connect to delete, edit, or disable the material in question, you must provide Rehab-Connect with all of the following information: (a) a physical or electronic signature of a person authorized to act on behalf of the owner of the exclusive right that is allegedly infringed; (b) identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single notification, a representative list of such works; (c) identification of the material that is claimed to be infringed or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit Rehab-Connect to locate the material; (d) information reasonably sufficient to permit Rehab-Connect to contact you, such as an address, telephone number, and if available, an electronic mail address at which you may be contacted; (e) a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and (f) a statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. For this notification to be effective, you must provide it to Rehab-Connect's designated agent at:
<br>
Support Team
<br>
Rehab-Connect
<br>
123 Center <br>
San Juan Capistrano, CA 92675<br>

info@rehab-connect.com
<br>
5. Trademarks
<br>
"Rehab-Connect," the Rehab-Connect logos and any other Rehab-Connect product or service name or slogan contained on the Site are trademarks of Rehab-Connect, and may not be copied, imitated or used, in whole or in part, without the prior written permission of Rehab-Connect or the applicable trademark holder. You may not use any metatags or any other "hidden text" utilizing "Rehab-Connect" or any other name, trademark or product or service name of Rehab-Connect without our prior written permission. In addition, the look and feel of the Site, including all page headers, custom graphics, button icons and scripts, is the service mark, trademark and/or trade dress of Rehab-Connect and may not be copied, imitated or used, in whole or in part, without our prior written permission. All other trademarks, registered trademarks, product names and Rehab-Connect names or logos mentioned in the Site are the property of their respective owners. Reference to any products, services, processes or other information, by trade name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation thereof by us.
<br>
6. Hyperlinks
<br>
You are granted a limited, non-transferable, non-exclusive license to create a text hyperlink to the Site for noncommercial purposes, provided that such link does not portray Rehab-Connect or any of its products and services in a false, misleading, derogatory or otherwise defamatory manner and provided further that the linking site does not contain any adult or illegal material or any material that is offensive, harassing or otherwise objectionable. This limited license may be revoked at any time. You may not use a Rehab-Connect logo or other proprietary graphic of Rehab-Connect to link to this Site without the express written permission of Rehab-Connect. Further, you may not use, frame or utilize framing techniques to enclose any Rehab-Connect trademark, logo or other proprietary information, including the images found at the Site, the content of any text or the layout/design of any page or form contained on a page on the Site without Rehab-Connect's express written consent. Except as noted above, you are not conveyed any right or license by implication, estoppel or otherwise in or under any patent, trademark, copyright or proprietary right of Rehab-Connect or any third-party.
<br>
Rehab-Connect makes no claim or representation regarding, and accepts no responsibility for, the quality, content, nature or reliability of third-party websites accessible via hyperlink or websites linking to the Site. Such sites are not under the control of Rehab-Connect and Rehab-Connect is not responsible for any embedded content or the content of any linked site or any link contained in a linked site, or any review, changes or updates to such sites. Rehab-Connect may provide these links as a convenience to you, but the inclusion of any link does not imply affiliation, endorsement or adoption by Rehab-Connect of any site or any information contained therein. When you leave the Site, you should be aware that our terms and policies no longer govern, and the policies of those third-party sites will apply. You should review the applicable terms and policies, including privacy and data gathering practices, of any site to which you navigate from the Site.
<br>
7. Advertisements and Promotions; Third-Party Products and Services
<br>
Rehab-Connect may run advertisements and promotions from third-parties on the Site or may otherwise provide information about or links to third-party products or services on the Site. Your business dealings or correspondence with, or participation in promotions of, such third-parties, and any terms, conditions, warranties or representations associated with such dealings or promotions, are solely between you and such third-party. Rehab-Connect is not responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or promotions or as the result of the presence of such non-Rehab-Connect advertisers or third-party information on the Site.
<br>
8. Submissions
<br>
You may submit questions, comments, suggestions, ideas, plans, notes, drawings, original or creative materials or other information about Rehab-Connect, the Site or our products and services (collectively, "Submissions"). Submissions, whether posted to the Site or provided to Rehab-Connect by email or otherwise, are non-confidential and will become the sole property of Rehab-Connect. Rehab-Connect will own exclusive rights, including all intellectual property rights, and will be entitled to the unrestricted use and dissemination of Submissions for any purpose, commercial or otherwise, without acknowledgement or compensation to you.
<br>
9. Affiliated Sites
<br>
Rehab-Connect has no control over, and no liability for any third-party websites or materials. Rehab-Connect works with a number of partners and affiliates whose Internet sites may be linked with the Site. Because neither Rehab-Connect nor the Site has control over the content and performance of these partner and affiliate sites, Rehab-Connect makes no guarantees about the accuracy, currency, content or quality of the information provided by such sites, and Rehab-Connect assumes no responsibility for unintended, objectionable, inaccurate, misleading or unlawful content that may reside on those sites. Similarly, from time to time in connection with your use of the Site, you may have access to content items (including, but not limited to, websites) that are owned by third-parties. You acknowledge and agree that Rehab-Connect makes no guarantees about, and assumes no responsibility for, the accuracy, currency, content or quality of this third-party content, and that, unless expressly provided otherwise, these Terms of Use will govern your use of any and all third-party content.
<br>
10. Prohibited Uses
<br>
Rehab-Connect imposes certain restrictions on your permissible use of the Site. You are prohibited from violating or attempting to violate any security features of the Site, including, without limitation, (a) accessing content or data not intended for you, or logging onto a server or account that you are not authorized to access; (b) attempting to probe, scan or test the vulnerability of the Site, or any associated system or network, or to breach security or authentication measures without proper authorization; (c) interfering or attempting to interfere with service to any user, host, or network, including, without limitation, by means of submitting a virus to the Site, overloading, "flooding," "spamming," "mail bombing" or "crashing;" (d) using the Site to send unsolicited e-mail, including, without limitation, promotions, or advertisements for products or services; (e) forging any TCP/IP packet header or any part of the header information in any e-mail or in any posting; or (f) attempting to modify, reverse-engineer, decompile, disassemble or otherwise reduce or attempt to reduce to a human-perceivable form any of the source code used by Rehab-Connect in providing the Site. Any violation of system or network security may subject you to civil and/or criminal liability.
<br>
11. Indemnity
<br>
You agree to indemnify Rehab-Connect for certain of your acts and omissions. You agree to indemnify, defend and hold harmless Rehab-Connect, its affiliates, officers, directors, employees, consultants, agents and representatives from any and all third-party claims, losses, liability, damages and/or costs (including reasonable attorneys' fees and costs) arising from your access to or use of the Site, your violation of these Terms of Use or your infringement, or infringement by any other user of your account, of any intellectual property or other right of any person or entity. Rehab-Connect will notify you promptly of any such claim, loss, liability or demand, and will provide you with reasonable assistance, at your expense, in defending any such claim, loss, liability, damage or cost.
<br>
12. Disclaimer
<br>
EXCEPT AS EXPRESSLY PROVIDED TO THE CONTRARY IN A WRITING BY Rehab-Connect, THE SITE AND THE SITE MATERIALS CONTAINED THEREIN ARE PROVIDED ON AN "AS IS" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. Rehab-Connect DISCLAIMS ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT AS TO THE SITE AND THE SERVICES, INCLUDING THE INFORMATION, CONTENT AND MATERIALS CONTAINED THEREIN. Rehab-Connect DOES NOT REPRESENT OR WARRANT THAT THE SITE OR SITE MATERIALS ARE ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE. WHILE Rehab-Connect ATTEMPTS TO MAKE YOUR ACCESS AND USE OF THE SITE SAFE, Rehab-Connect CANNOT AND DOES NOT REPRESENT OR WARRANT THAT THE SITE OR ITS SERVER(S) ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; THEREFORE, YOU SHOULD USE INDUSTRY-RECOGNIZED SOFTWARE TO DETECT AND DISINFECT VIRUSES FROM ANY DOWNLOAD.
<br>
13. Limitation of Liability
<br>
IN NO EVENT WILL Rehab-Connect, ITS MEMBERS, DIRECTORS, OFFICERS, EMPLOYEES OR AGENTS BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND, INCLUDING BUT NOT LIMITED TO LOSS OF USE, LOSS OF PROFITS OR LOSS OF DATA, WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE) OR OTHERWISE, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF OR INABILITY TO USE THE SITE, THE CONTENT OR THE MATERIALS CONTAINED IN OR ACCESSED THROUGH THE SITE, INCLUDING, WITHOUT LIMITATION, ANY DAMAGES CAUSED BY OR RESULTING FROM RELIANCE BY YOU ON ANY INFORMATION OBTAINED FROM Rehab-Connect, OR THAT RESULT FROM MISTAKES, OMISSIONS, INTERRUPTIONS, DELETION OF FILES OR EMAIL, ERRORS, DEFECTS, VIRUSES, DELAYS IN OPERATION OR TRANSMISSION OR ANY FAILURE OF PERFORMANCE, WHETHER OR NOT RESULTING FROM ACTS OF GOD, COMMUNICATIONS FAILURE, THEFT, DESTRUCTION OR UNAUTHORIZED ACCESS TO Rehab-Connect'S RECORDS, PROGRAMS OR SERVICES. IN NO EVENT WILL THE AGGREGATE LIABILITY OF Rehab-Connect, WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE, WHETHER ACTIVE, PASSIVE OR IMPUTED), PRODUCT LIABILITY, STRICT LIABILITY OR OTHER THEORY, ARISING OUT OF OR RELATING TO THE USE OF OR INABILITY TO USE THE SITE OR TO THESE TERMS OF USE EXCEED ANY COMPENSATION YOU PAY, IF ANY, TO Rehab-Connect FOR ACCESS TO OR USE OF THE SITE. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF LIABILITY IN CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THESE LIMITATIONS OF LIABILITY MAY NOT APPLY TO YOU.
<br>
14. Governing Law
<br>
These Terms of Use will be construed in accordance with and governed by the laws of the United States and the State of California, without reference to their rules regarding conflicts of law.
<br>
15. Arbitration
<br>
PLEASE READ THE FOLLOWING PARAGRAPH CAREFULLY BECAUSE IT REQUIRES YOU TO ARBITRATE DISPUTES WITH Rehab-Connect AND IT LIMITS THE MANNER IN WHICH YOU CAN SEEK RELIEF.
<br>
You and Rehab-Connect agree to arbitrate any dispute arising from these Terms of Use or relating to the Site and Site Materials, except that you and Rehab-Connect are NOT required to arbitrate any dispute in which either party seeks equitable or other relief for the alleged unlawful use of copyrights, trademarks, trade names, logos, trade secrets or patents. ARBITRATION PREVENTS YOU FROM SUING IN COURT OR FORM HAVING A JURY TRIAL. You and Rehab-Connect agree: (i) to notify each other of any dispute within thirty (30) days of when it arises; (ii) to attempt informal resolution prior to any demand for arbitration; (iii) that any arbitration will occur in Orange County, California; and (iv) that arbitration will be conducted confidentially by a single arbitrator in accordance with the Rules of the American Arbitration Association. You and Rehab-Connect also agree that the state or federal courts in Santa Clara County, California have exclusive jurisdiction over any appeals of an arbitration award and over any suit between the parties not subject to arbitration. Other than class procedures and remedies discussed below, the arbitrator has the authority to grant any remedy that would otherwise be available in court. Whether the dispute is heard in arbitration or in court, you and Rehab-Connect will not commence against the other a class action, class arbitration or other representative action or proceeding.
<br>
16. California Use Only
<br>
The Site is controlled and operated by Rehab-Connect from its offices in the State of California. Rehab-Connect makes no representation that any of the materials or the services to which you have been given access are available or appropriate for use in other locations. Your use of or access to the Site should not be construed as Rehab-Connect's purposefully availing itself of the benefits or privilege of doing business in any state or jurisdiction other than California.
<br>
17. Severability and Waiver
<br>
If, for whatever reason, a court of competent jurisdiction finds any term or condition in these Terms of Use to be unenforceable, all other terms and conditions will remain unaffected and in full force and effect. No waiver of any breach of any provision of these Terms of Use will constitute a waiver of any prior, concurrent, or subsequent breach of the same or any other provisions hereof, and no waiver will be effective unless made in writing and signed by an authorized representative of the waiving party.
<br>
18. Modifications
<br>
Rehab-Connect may, in its sole discretion and without prior notice, (a) revise these Terms of Use; (b) modify the Site, or any features or portions thereof; and (c) discontinue the Site, or any features or portions thereof, at any time. Rehab-Connect will post any revision to these Terms of Use to the Site, and the revision will be effective immediately on such posting. You agree to review these Terms of Use and other online policies posted on the Site periodically to be aware of any revisions. You agree that, by continuing to use or access the Site following notice of any revision, you will abide by any such revision.
<br>
19. Acknowledgement
<br>
BY USING THE SERVICE OR ACCESSING THE SITE, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF USE AND AGREE TO BE BOUND BY THEM.


